import Head from "next/head";
import { useEffect, useState } from "react";

export default function Home() {
  const [count, setCount] = useState(0);
  const [key, setKey] = useState("");
  useEffect(() => {
    if (typeof window.DeviceMotionEvent != "undefined") {
      window.addEventListener("devicemotion", handleMotionEvent, true);
    }
  }, []);

  const handleMotionEvent = (event: any) => {
    const x = event.accelerationIncludingGravity.x;
    const y = event.accelerationIncludingGravity.y;
    const z = event.accelerationIncludingGravity.z;

    const key = `${x},${y},${z}`;

    setKey(key);
    setCount((prev) => prev + 1);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-[200vh]">
        {count}: {key}
      </main>
    </>
  );
}
